### ISSUE TITLE
[Vanilla Bug] Game intern brush has upper left tile missing

### ISSUE THREAD

**Issue by TheRedDaemon** [gynt/stronghold-mapeditortools#10]
The game always had the issue (or is it a "feature"?) that brushes, starting with size 3, have a missing tile in the upper left.

It would be good if this tile could be added to the brush, since the game intern brush can not be mirrored.
This results in faulty mirrored actions, since regardless of the options, the action always lacks the upper left tile.

**Comment by gynt** [comment]
I will see if I can change this in the .exe

**Comment by TheRedDaemon** [comment]
Just a small thing I noticed:
If used at the edges of the maps, the brush extends. This is the most noticeable when using the biggest brush.
If used that way, the resulting tiles might be partially displayed wrong until the map around them is updated again.

So it seems that it is less a stamp and more a collection of tiles that spread out in a certain way?
Units behave similar, although they gather in a different formation. If an army is ordered to gather at the map border the formation also spreads out.
Maybe the behavior is related, if not computationally, maybe concept-wise?

**Comment by TheRedDaemon** [comment]
Closing this, since it has been fixed for a while.

There was even another effect of the fixed tile outside of the easily visible. The results of the hill and the mountain tools now produce a symmentrical shape if applied to the same tile multiple times.
I once mentioned this (now solved) issue a bit of topic [HERE](https://github.com/gynt/stronghold-mapeditortools/issues/12#issuecomment-830920999).
