### ISSUE TITLE
Mirror Mode effects moat placement during gameplay

### ISSUE THREAD

**Issue by TheRedDaemon** [gynt/stronghold-mapeditortools#2]
Just as a small information, if it is not already known:
If mirroring is active, the moat place and delete tools behave like terrain tools and are mirrored, regardless of the game mode.

**Comment by gynt** [comment]
That is hilarious. I might have forgotten a gamemode check because I assumed map editor game commands are only available in editor mode. I guess I was wrong! I will fix it.

**Comment by gynt** [comment]
fixed!
